Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
RESUME_ROOT_DIR = os.path.expanduser('~/Documents/resume_data/data/data')
PERSIST_ROOT_DIR = os.path.expanduser('~/Documents/resume_data/persist')

from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader(os.path.join(RESUME_ROOT_DIR,'FITNESS','10428916.pdf'))
pages = loader.load_and_split()

print(pages[0].page_content[:550])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 6[0m
[1;32m      3[0m PERSIST_ROOT_DIR [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser([38;5;124m'[39m[38;5;124m~/Documents/resume_data/persist[39m[38;5;124m'[39m)
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlangchain[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdocument_loaders[39;00m [38;5;28;01mimport[39;00m PyPDFLoader
[0;32m----> 6[0m loader [38;5;241m=[39m [43mPyPDFLoader[49m[43m([49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[43mRESUME_ROOT_DIR[49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mFITNESS[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43m10428916.pdf[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m)[49m
[1;32m      7[0m pages [38;5;241m=[39m loader[38;5;241m.[39mload_and_split()
[1;32m      9[0m [38;5;28mprint[39m(pages[[38;5;241m0[39m][38;5;241m.[39mpage_content[:[38;5;241m550[39m])

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/langchain/document_loaders/pdf.py:157[0m, in [0;36mPyPDFLoader.__init__[0;34m(self, file_path, password, headers, extract_images)[0m
[1;32m    153[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m    154[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m    155[0m         [38;5;124m"[39m[38;5;124mpypdf package not found, please install it with [39m[38;5;124m"[39m [38;5;124m"[39m[38;5;124m`pip install pypdf`[39m[38;5;124m"[39m
[1;32m    156[0m     )
[0;32m--> 157[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43mfile_path[49m[43m,[49m[43m [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m)[49m
[1;32m    158[0m [38;5;28mself[39m[38;5;241m.[39mparser [38;5;241m=[39m PyPDFParser(password[38;5;241m=[39mpassword, extract_images[38;5;241m=[39mextract_images)

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/llm-env/lib/python3.11/site-packages/langchain/document_loaders/pdf.py:100[0m, in [0;36mBasePDFLoader.__init__[0;34m(self, file_path, headers)[0m
[1;32m     98[0m         [38;5;28mself[39m[38;5;241m.[39mfile_path [38;5;241m=[39m [38;5;28mstr[39m(temp_pdf)
[1;32m     99[0m [38;5;28;01melif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39misfile([38;5;28mself[39m[38;5;241m.[39mfile_path):
[0;32m--> 100[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mFile path [39m[38;5;132;01m%s[39;00m[38;5;124m is not a valid file or url[39m[38;5;124m"[39m [38;5;241m%[39m [38;5;28mself[39m[38;5;241m.[39mfile_path)

[0;31mValueError[0m: File path /Users/williamthompson/Documents/resume_data/data/data/FITNESS/10428916.pdf is not a valid file or url

